"""
Report generators for audit results.
"""

import json
from abc import ABC, abstractmethod
from datetime import datetime
from typing import Any, Dict, List
import logging

logger = logging.getLogger(__name__)


class ReportGenerator(ABC):
    """Abstract base class for report generators."""

    @abstractmethod
    def generate(self, results: Dict[str, Any]) -> str:
        """Generate report from audit results."""
        pass


class MarkdownReport(ReportGenerator):
    """Generate Markdown format reports."""

    def generate(self, results: Dict[str, Any]) -> str:
        """Generate a comprehensive Markdown report."""
        sections = []

        # Header
        sections.append(self._generate_header(results))

        # Executive Summary
        sections.append(self._generate_executive_summary(results))

        # Findings by Severity
        sections.append(self._generate_findings_section(results))

        # Recommendations
        sections.append(self._generate_recommendations_section(results))

        # Agent Results
        sections.append(self._generate_agent_results(results))

        # Dependency Graph
        sections.append(self._generate_dependency_graph(results))

        return '\n\n'.join(sections)

    def _generate_header(self, results: Dict[str, Any]) -> str:
        """Generate report header."""
        audit_id = results.get('audit_id', 'N/A')
        start_time = results.get('start_time', 'N/A')
        duration = results.get('duration_seconds', 0)

        return f"""# PostgreSQL Database Audit Report

**Audit ID:** {audit_id}
**Date:** {start_time}
**Duration:** {duration:.2f} seconds
**Generated by:** PMA-Agent v1.0.0

---"""

    def _generate_executive_summary(self, results: Dict[str, Any]) -> str:
        """Generate executive summary."""
        metrics = results.get('metrics', {})
        findings = results.get('findings', [])

        # Count by severity
        severity_counts = {}
        for f in findings:
            sev = f.get('severity', 'info')
            severity_counts[sev] = severity_counts.get(sev, 0) + 1

        critical = severity_counts.get('critical', 0)
        high = severity_counts.get('high', 0)
        medium = severity_counts.get('medium', 0)
        low = severity_counts.get('low', 0)
        info = severity_counts.get('info', 0)

        summary = f"""## Executive Summary

### Overview

| Metric | Value |
|--------|-------|
| Total Findings | {len(findings)} |
| Critical Issues | {critical} |
| High Issues | {high} |
| Medium Issues | {medium} |
| Low Issues | {low} |
| Informational | {info} |
| Agents Completed | {metrics.get('agents_completed', 0)} |

### Risk Assessment

"""
        if critical > 0:
            summary += "**CRITICAL:** Immediate action required. Critical security or data integrity issues found.\n\n"
        elif high > 0:
            summary += "**HIGH:** Significant issues found that should be addressed promptly.\n\n"
        elif medium > 0:
            summary += "**MEDIUM:** Issues found that should be reviewed and addressed.\n\n"
        else:
            summary += "**LOW:** Database is in good condition with minor improvements suggested.\n\n"

        return summary

    def _generate_findings_section(self, results: Dict[str, Any]) -> str:
        """Generate findings section."""
        findings = results.get('findings', [])

        if not findings:
            return "## Findings\n\nNo issues found."

        sections = ["## Findings"]

        # Group by severity
        for severity in ['critical', 'high', 'medium', 'low', 'info']:
            sev_findings = [f for f in findings if f.get('severity') == severity]
            if not sev_findings:
                continue

            sections.append(f"\n### {severity.upper()} ({len(sev_findings)})\n")

            for f in sev_findings:
                sections.append(f"""#### {f.get('title', 'Untitled')}

- **Category:** {f.get('category', 'N/A')}
- **Agent:** {f.get('agent', 'N/A')}
- **Affected Objects:** {', '.join(f.get('affected_objects', [])) or 'N/A'}

{f.get('description', '')}

**Remediation:** {f.get('remediation', 'N/A')}

---
""")

        return '\n'.join(sections)

    def _generate_recommendations_section(self, results: Dict[str, Any]) -> str:
        """Generate recommendations section."""
        recommendations = results.get('recommendations', [])

        if not recommendations:
            return "## Recommendations\n\nNo specific recommendations."

        sections = ["## Recommendations"]

        # Sort by priority
        sorted_recs = sorted(recommendations, key=lambda x: x.get('priority', 0), reverse=True)

        for i, rec in enumerate(sorted_recs, 1):
            sections.append(f"""### {i}. {rec.get('title', 'Untitled')}

- **Priority:** {rec.get('priority', 0)}/10
- **Category:** {rec.get('category', 'N/A')}
- **Effort:** {rec.get('effort', 'N/A')}
- **Impact:** {rec.get('impact', 'N/A')}

{rec.get('description', '')}

**Implementation:**
```sql
{rec.get('implementation', 'N/A')}
```

---
""")

        return '\n'.join(sections)

    def _generate_agent_results(self, results: Dict[str, Any]) -> str:
        """Generate agent results summary."""
        agent_results = results.get('agent_results', {})

        if not agent_results:
            return "## Agent Results\n\nNo agent results available."

        sections = ["## Agent Results Summary"]

        for agent_name, result in agent_results.items():
            sections.append(f"\n### {agent_name}\n")

            # Show key metrics from each agent
            if isinstance(result, dict):
                for key, value in result.items():
                    if key not in ('duration_seconds',) and not isinstance(value, (list, dict)):
                        sections.append(f"- **{key}:** {value}")

                duration = result.get('duration_seconds', 0)
                sections.append(f"- **Duration:** {duration:.2f}s\n")

        return '\n'.join(sections)

    def _generate_dependency_graph(self, results: Dict[str, Any]) -> str:
        """Generate table dependency information."""
        agent_results = results.get('agent_results', {})
        fk_result = agent_results.get('integrity', {})

        if not fk_result:
            return ""

        graph = fk_result.get('relationship_graph', {})
        if not graph:
            return ""

        sections = ["## Table Relationships"]

        sections.append("\n```mermaid\ngraph TD")

        for table, relations in graph.items():
            for ref in relations.get('references', []):
                sections.append(f"    {table} --> {ref}")

        sections.append("```\n")

        return '\n'.join(sections)


class HTMLReport(ReportGenerator):
    """Generate HTML format reports."""

    def generate(self, results: Dict[str, Any]) -> str:
        """Generate HTML report."""
        md_report = MarkdownReport()
        md_content = md_report.generate(results)

        # Basic HTML wrapper with styling
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PostgreSQL Audit Report - {results.get('audit_id', 'N/A')}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            line-height: 1.6;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background: #f5f5f5;
        }}
        .container {{
            background: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        h1 {{ color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }}
        h2 {{ color: #34495e; border-bottom: 2px solid #ecf0f1; padding-bottom: 8px; }}
        h3 {{ color: #7f8c8d; }}
        table {{ border-collapse: collapse; width: 100%; margin: 15px 0; }}
        th, td {{ border: 1px solid #ddd; padding: 12px; text-align: left; }}
        th {{ background: #3498db; color: white; }}
        tr:nth-child(even) {{ background: #f9f9f9; }}
        code {{ background: #f4f4f4; padding: 2px 6px; border-radius: 3px; }}
        pre {{ background: #2c3e50; color: #ecf0f1; padding: 15px; border-radius: 5px; overflow-x: auto; }}
        .critical {{ color: #e74c3c; font-weight: bold; }}
        .high {{ color: #e67e22; font-weight: bold; }}
        .medium {{ color: #f39c12; }}
        .low {{ color: #3498db; }}
        .info {{ color: #95a5a6; }}
        hr {{ border: none; border-top: 1px solid #ecf0f1; margin: 20px 0; }}
    </style>
</head>
<body>
    <div class="container">
        <div id="content">
            {self._md_to_html(md_content)}
        </div>
    </div>
</body>
</html>"""
        return html

    def _md_to_html(self, md: str) -> str:
        """Basic markdown to HTML conversion."""
        import re

        html = md

        # Headers
        html = re.sub(r'^#### (.+)$', r'<h4>\1</h4>', html, flags=re.MULTILINE)
        html = re.sub(r'^### (.+)$', r'<h3>\1</h3>', html, flags=re.MULTILINE)
        html = re.sub(r'^## (.+)$', r'<h2>\1</h2>', html, flags=re.MULTILINE)
        html = re.sub(r'^# (.+)$', r'<h1>\1</h1>', html, flags=re.MULTILINE)

        # Bold
        html = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html)

        # Code blocks
        html = re.sub(r'```sql\n(.*?)```', r'<pre><code>\1</code></pre>', html, flags=re.DOTALL)
        html = re.sub(r'```\n(.*?)```', r'<pre><code>\1</code></pre>', html, flags=re.DOTALL)

        # Inline code
        html = re.sub(r'`(.+?)`', r'<code>\1</code>', html)

        # Lists
        html = re.sub(r'^- (.+)$', r'<li>\1</li>', html, flags=re.MULTILINE)

        # Tables (basic)
        lines = html.split('\n')
        in_table = False
        new_lines = []
        for line in lines:
            if '|' in line and '---' not in line:
                if not in_table:
                    new_lines.append('<table>')
                    in_table = True
                cells = [c.strip() for c in line.split('|')[1:-1]]
                row = '<tr>' + ''.join(f'<td>{c}</td>' for c in cells) + '</tr>'
                new_lines.append(row)
            else:
                if in_table and '|' not in line:
                    new_lines.append('</table>')
                    in_table = False
                new_lines.append(line)

        html = '\n'.join(new_lines)

        # Horizontal rules
        html = html.replace('---', '<hr>')

        # Paragraphs
        html = re.sub(r'\n\n', '</p><p>', html)

        return f'<p>{html}</p>'


class JSONReport(ReportGenerator):
    """Generate JSON format reports."""

    def generate(self, results: Dict[str, Any]) -> str:
        """Generate JSON report."""
        # Create a clean copy for JSON export
        report = {
            'meta': {
                'audit_id': results.get('audit_id'),
                'start_time': results.get('start_time'),
                'end_time': results.get('end_time'),
                'duration_seconds': results.get('duration_seconds'),
                'version': '1.0.0'
            },
            'summary': results.get('metrics', {}),
            'findings': results.get('findings', []),
            'recommendations': results.get('recommendations', []),
            'agent_results': results.get('agent_results', {}),
        }

        return json.dumps(report, indent=2, default=str)


def generate_report(results: Dict[str, Any], format: str = 'markdown') -> str:
    """Generate report in specified format."""
    generators = {
        'markdown': MarkdownReport,
        'md': MarkdownReport,
        'html': HTMLReport,
        'json': JSONReport,
    }

    generator_class = generators.get(format.lower())
    if not generator_class:
        raise ValueError(f"Unsupported format: {format}")

    generator = generator_class()
    return generator.generate(results)
